function param = PlotProps()
%PlotProps specifies plot properties
%   Detailed explanation goes here

param.fillSign = true;

param.analysisOpts = {'choose analysis', 'compare TC', 'tuning curve', 'waveform','pupil size all', ...
    'pupil size onset', 'pupil size change', 'gain change',...
    'time course of spike rate', 'time course of gain change',...
    'time course of wave width',...
    'fano factor (CL)', ...
    'fano factor (Mitchel)', 'fano factor (Churchl)', 'lfp (time domain)', ...
    'lfp (frequ domain)', 'noise correlation', 'signal correlation', 'ALL: fano factor (Mitchel)'};

param.clusterOpts = {'choose cluster', 'c1', 'c1/c0', 'lfp'};

param.axisOpts = {...
    'nonparam area ratio', 'nonparam area ratio 2nd half'...
    'MI', ...
    'gain change', 'additive change', 'additive change (rel)',...
    'gain co', 'off co', ...
    'dose', 'volt', ...
    'delta n to 1st 5HT app', 'delta t to 1st 5HT app', 't of 5HT app before' ...
    'phase selectivity', 'phase selectivity drug','phase selectivity diff', ...    
    'gauss fit mu base', 'gauss fit mu drug', 'gauss fit mu diff', ...
    'gauss fit sig base', 'gauss fit sig drug', 'gauss fit sig diff', ...
    'gauss fit a base', 'gauss fit a drug', 'gauss fit a diff', ...
    'gauss fit b base', 'gauss fit b drug', 'gauss fit b diff', ...
    'co fit m base', 'co fit m drug', 'co fit m diff', ...
    'co fit n base', 'co fit n drug', 'co fit n diff', ...
    'rmax drug', 'rmax base', 'rmax diff', ...
    'c50 base', 'c50 drug', 'c50 diff', ...    
    'SI base', 'SI drug', 'SI diff', ...
    'pref size base', 'pref size drug', 'pref size diff', ...
    'gauss ratio fit width center',  'gauss ratio fit width center drug',...
    'gauss ratio fit width surround',  'gauss ratio fit width surround drug', ...
    'gauss ratio fit gain center',  'gauss ratio fit gain center drug', ...
    'gauss ratio fit gain surround',  'gauss ratio fit gain surround drug', ...
     'r2 ag', 'r2 cg', 'r2 rg', 'a ag', 'a cg', 'a rg', ...
    'r2 rg cg diff', 'r2 ag cg diff', ...    
    'pf stim raw base', 'pf stim raw drug', 'pf stim raw diff', ...
    'blank base', 'blank drug', 'blank diff', ...
    'SMI', 'BRI ACF base', 'BRI ACF drug', 'BRI ACF diff', ...
    'BRI ISI base', 'BRI ISI drug', 'BRI ISI diff', ...
    'electrode depth', ...
    'latency base', 'latency drug', 'latency diff', ...
    'latency hmax base', 'latency hmax drug', 'latency hmax diff', ...
    'latency base corrected', 'latency drug corrected', 'latency diff corrected', ...
    'correction factor', ...
    'blank/or ratio base', 'blank/or ratio drug', 'blank/or ratio diff', ...
    'smallest response drug', 'smallest response', 'smallest response overall', ...
    'response duration', 'response duration drug', 'response duration diff', ...
    'latnoise', 'latnoise drug', 'latnoise diff',...
    'predicted latency', 'predicted latency drug', 'predicted latency diff', ...
    'predicted - true latency', 'predicted - true latency drug', ...   
    'RF width x', 'RF width y', 'RF width mean', 'RF ecc corr', 'eccentricity',... 
    'mean spike rate base', 'mean spike rate drug',...
    'mean spike rate diff', ...
    'geometric mean c1-c0', ...
    'noise correlation', 'noise correlation drug', ...
    'noise correlation diff', ...
    'noise correlation corrected', 'noise correlation drug corrected', ...
    'noise correlation diff corrected', ...
    'signal correlation', 'signal correlation drug', ...
    'signal correlation diff',  ...
     'noise correlation 2nd half', 'noise correlation drug 2nd half', ...
    'noise correlation diff 2nd half', ...
    'noise correlation 2nd half corrected', 'noise correlation drug 2nd half corrected', ...
    'noise correlation diff 2nd half corrected', ...
    'signal correlation 2nd half', 'signal correlation drug 2nd half', ...
    'signal correlation diff 2nd half', ...
    'wave width', 'experiment time', ...
    'tc ampl base', 'tc ampl drug', 'tc ampl diff',...
    'fano factor base', 'fano factor drug', 'fano factor diff', ...
    'fano factor 2nd half base', 'fano factor 2nd half drug', 'fano factor 2nd half diff', ...
    'fano factor fit base', 'fano factor fit drug', 'fano factor fit diff', ...
    'fano factor mitchel variance', 'fano factor mitchel bins', ...
    'isolation quality max', 'isolation quality base', 'isolation quality drug', 'r2', 'pupil size'};
% , 'spike field coherence'};

param.faceColorOpts = {'face color nothing', ...
    '[expInfo(incl_i).is5HT]', ...
    '[expInfo(incl_i).isadapt]',...
    '[expInfo(incl_i).isRC]',...
    'r2', 'gainchange', 'r2 gauss'};

param.edgeColorOpts = {'edge color nothing', 'ocularity'};

param.markerOpts = {'mark nothing', 'stimulus condition'};

param.markerfacecol = [1 0 0];

param.stimulicond = {'all stimuli cond', 'or', 'sf', 'co', 'sz', 'RC', 'adapt'};

param.eyeopts =  {'all', 'dominant eye', 'non-dominant eye'};

param.datacrit = {'all', 'best r2', 'first ex', 'highest dose', 'lowest dose'};

param.electrodecrit = {'all', 'unbroken and included broken ones',...
    'unbroken only', 'included broken ones', 'broken only', 'neg volt'};


end

