function KakiSpikeSortingFile = importfile(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   KAKISPIKESORTINGFILE = IMPORTFILE1(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   KAKISPIKESORTINGFILE = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   KakiSpikeSortingFile = importfile1('Kaki_SpikeSortingFile.csv', 1, 2952);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/07/13 14:09:04

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,7,9,10,11,13]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [3,4,7,10,11,13]);
rawStringColumns = string(raw(:, [1,2,5,6,8,9,12,14,15,16]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [4,6,9]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
KakiSpikeSortingFile = table;
KakiSpikeSortingFile.recordingdate = rawStringColumns(:, 1);
KakiSpikeSortingFile.gridposition = rawStringColumns(:, 2);
KakiSpikeSortingFile.sessionID = cell2mat(rawNumericColumns(:, 1));
KakiSpikeSortingFile.trellisfilenumber = cell2mat(rawNumericColumns(:, 2));
KakiSpikeSortingFile.matfilename = rawStringColumns(:, 3);
KakiSpikeSortingFile.iontophoresis = rawStringColumns(:, 4);
KakiSpikeSortingFile.voltage = cell2mat(rawNumericColumns(:, 3));
KakiSpikeSortingFile.resistance = rawStringColumns(:, 5);
KakiSpikeSortingFile.isolationquality = rawStringColumns(:, 6);
KakiSpikeSortingFile.plxfilerange = cell2mat(rawNumericColumns(:, 4));
KakiSpikeSortingFile.includedtrials = cell2mat(rawNumericColumns(:, 5));
KakiSpikeSortingFile.electodebroken = categorical(rawStringColumns(:, 7));
KakiSpikeSortingFile.commentelectrode = cell2mat(rawNumericColumns(:, 6));
KakiSpikeSortingFile.generalcomment = rawStringColumns(:, 8);
KakiSpikeSortingFile.includedtoanalysis = rawStringColumns(:, 9);
KakiSpikeSortingFile.excludedduetoelectordes = categorical(rawStringColumns(:, 10));

KakiSpikeSortingFile = table2struct(KakiSpikeSortingFile);

%% adjust output variable
for kk = 1:length(KakiSpikeSortingFile)
    matfilename{kk} = KakiSpikeSortingFile(kk).matfilename{1};
    iontophoresis{kk} = KakiSpikeSortingFile(kk).iontophoresis{1};
    isolationquality{kk} = KakiSpikeSortingFile(kk).isolationquality{1};
end

[KakiSpikeSortingFile.matfilename] = deal(matfilename{:});
[KakiSpikeSortingFile.iontophoresis] = deal(iontophoresis{:});
[KakiSpikeSortingFile.isolationquality] = deal(isolationquality{:});



