function s = infospectitle( exinfo )
% information from the exinfo structure called with name and value in a title
%



if ~isempty(exinfo.fitparam)
s = sprintf(['#%1.0f ' exinfo.cluster  ...
            ' me=%1.0f'  ...
            ' RC=%1.0f          adapt=%1.0f \n\n ' ...
            ' gain=%1.2f     add= %1.2f      r2=%1.2f \n'...
            ' base: mu=%1.2f    sig=%1.2f    r2=%1.2f \n'...
            ' drug: mu=%1.2f    sig=%1.2f    r2=%1.2f \n'...
            ' wavewdt=%1.0f    \n'...
            ' latency base: %1.0f ms, latency drug: %1.0f ms'],  ...
            exinfo.id, ...
            exinfo.ocul, exinfo.isRC, exinfo.isadapt, exinfo.gslope,  exinfo.yoff, exinfo.rsqr_both,...
            exinfo.fitparam.mu, exinfo.fitparam.sig, exinfo.fitparam.r2, ...
            exinfo.fitparam_drug.mu, exinfo.fitparam_drug.sig, exinfo.fitparam_drug.r2,...
            exinfo.wdt, exinfo.lat, exinfo.lat_drug);

else
    s = sprintf(['#%1.0f ' exinfo.cluster  ...
            ' me=%1.0f'  ...
            ' RC=%1.0f          adapt=%1.0f' '\n\n ' ...
            ' wavewdt=%1.0f     gain=%1.2f      add= %1.2f      r2=%1.2f \n'...
            ' rsc=%1.2f         p=%1.2f \n'  ...
            ' rsig=%1.2f        p=%1.2f \n'  ...
            ' rsc_{drug}=%1.2f      p=%1.2f \n'  ...
            ' rsig_{drug}=%1.2f     p=%1.2f \n' ...
            ' latency base: %1.0f ms, latency drug: %1.0f ms'],  ...
            exinfo.id, ...
            exinfo.ocul, exinfo.isRC, exinfo.isadapt, exinfo.wdt,  exinfo.gslope,  exinfo.yoff, exinfo.rsqr_both,...
            exinfo.rsc, exinfo.prsc, exinfo.rsig, exinfo.prsig,...
            exinfo.rsc_drug, exinfo.prsc_drug, exinfo.rsig_drug, exinfo.prsig_drug,...
            exinfo.lat, exinfo.lat_drug);

end
    

end

