function s = infospectitle( info )

if ~isempty(info.fitparam)
% s = sprintf(['#%1.0f ' info.cluster  ...
%             ' me=%1.0f'  ...
%             ' RC=%1.0f          adapt=%1.0f \n\n ' ...
%             ' wavewdt=%1.0f                  gain=%1.2f     add= %1.2f      r2=%1.2f \n'...
%             ' base: mu=%1.2f    sig=%1.2f    a=%1.2f        b=%1.2f         r2=%1.2f \n'...
%             ' drug: mu=%1.2f    sig=%1.2f    a=%1.2f        b=%1.2f         r2=%1.2f \n'...
%             ' hn base: mu=%1.2f    sig=%1.2f    a=%1.2f        b=%1.2f      \n'...
%             ' hn drug: mu=%1.2f    sig=%1.2f    a=%1.2f        b=%1.2f      \n'...
%             ' base: rsc=%1.2f      p=%1.2f          rsig=%1.2f     p=%1.2f \n'  ...
%             ' drug: rsc=%1.2f      p=%1.2f          rsig=%1.2f     p=%1.2f \n' ...
%             ' latency base: %1.0f ms, latency drug: %1.0f ms'],  ...
%             info.id, ...
%             info.ocul, info.isRC, info.isadapt, info.wdt,  info.gslope,  info.yoff, info.rsqr_both,...
%             info.fitparam.mu, info.fitparam.sig, info.fitparam.a, info.fitparam.b, info.fitparam.r2, ...
%             info.fitparam_drug.mu, info.fitparam_drug.sig, info.fitparam_drug.a, info.fitparam_drug.b, info.fitparam_drug.r2,...
%             info.fitparam.HN.mean, info.fitparam.HN.sd, info.fitparam.HN.amp, info.fitparam.HN.base,  ...
%             info.fitparam_drug.HN.mean, info.fitparam_drug.HN.sd, info.fitparam_drug.HN.amp, info.fitparam_drug.HN.base,  ...
%             info.rsc, info.prsc, info.rsig, info.prsig,...
%             info.rsc_drug, info.prsc_drug, info.rsig_drug, info.prsig_drug, ...
%             info.lat, info.lat_drug);
s = sprintf(['#%1.0f ' info.cluster  ...
            ' me=%1.0f'  ...
            ' RC=%1.0f          adapt=%1.0f \n\n ' ...
            ' gain=%1.2f     add= %1.2f      r2=%1.2f \n'...
            ' base: mu=%1.2f    sig=%1.2f    r2=%1.2f \n'...
            ' drug: mu=%1.2f    sig=%1.2f    r2=%1.2f \n'...
            ' wavewdt=%1.0f    \n'...
            ' latency base: %1.0f ms, latency drug: %1.0f ms'],  ...
            info.id, ...
            info.ocul, info.isRC, info.isadapt, info.gslope,  info.yoff, info.rsqr_both,...
            info.fitparam.mu, info.fitparam.sig, info.fitparam.r2, ...
            info.fitparam_drug.mu, info.fitparam_drug.sig, info.fitparam_drug.r2,...
            info.wdt, info.lat, info.lat_drug);

else
    s = sprintf(['#%1.0f ' info.cluster  ...
            ' me=%1.0f'  ...
            ' RC=%1.0f          adapt=%1.0f' '\n\n ' ...
            ' wavewdt=%1.0f     gain=%1.2f      add= %1.2f      r2=%1.2f \n'...
            ' rsc=%1.2f         p=%1.2f \n'  ...
            ' rsig=%1.2f        p=%1.2f \n'  ...
            ' rsc_{drug}=%1.2f      p=%1.2f \n'  ...
            ' rsig_{drug}=%1.2f     p=%1.2f \n' ...
            ' latency base: %1.0f ms, latency drug: %1.0f ms'],  ...
            info.id, ...
            info.ocul, info.isRC, info.isadapt, info.wdt,  info.gslope,  info.yoff, info.rsqr_both,...
            info.rsc, info.prsc, info.rsig, info.prsig,...
            info.rsc_drug, info.prsc_drug, info.rsig_drug, info.prsig_drug,...
            info.lat, info.lat_drug);

end
    

end

